/**:  # global parameters
  ros__parameters:
    dds_baudrate: 2000000
    gcs_ip: 192.168.1.50  # 127.0.0.1 or 192.168.1.10
    lasting_time: 70
    task_allocation:
      control:    10 # dev id
      optimize:   10
      plugin:     10